# Generated by Django 3.0.3 on 2020-05-21 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_news_ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chname', models.CharField(max_length=50)),
                ('chimg', models.ImageField(default='noimg.jpg', upload_to='uploads/chimg')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
                ('reg_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='none.jpg', upload_to='stationary')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('query', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='pna.jpg', upload_to='uploads/posts')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(upload_to='uploads/slider')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Rajasthan', 'Rajasthan'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Maharastra', 'Maharastra'), ('Gujrat', 'Gujrat'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Bihar', 'Bihar')], default='', max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WelMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg1', models.TextField()),
                ('msg2', models.TextField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('img', models.ImageField(default='pna.jpg', upload_to='uploads/posts')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_news.Categories')),
                ('ch_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_news.Add_news_ch')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_news.City')),
                ('related_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_news.RelImg')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_news.State')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chimg', models.ImageField(default='ch_cover.jpg', upload_to='uploads/chcover')),
                ('owner_name', models.CharField(max_length=50)),
                ('Ch_desc', models.TextField()),
                ('since', models.DateField(default=datetime.datetime.today)),
                ('language', models.CharField(choices=[('h', 'Hindi'), ('e', 'English'), ('m', 'marathi'), ('g', 'gujrati'), ('t', 'tamil'), ('p', 'punjabi')], default='', max_length=15)),
                ('ch_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kg_news.Add_news_ch')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_news.SubCategory'),
        ),
    ]
